import card_body_imgs from "@/public/home/card-body-imgs/card-body-imgs";
import partners from "@/public/partners/partners";

const card_infos = [
  {
    id: "1",
    title: "Ingage",
    description: "Ingage Web Page",
    color: "#fff",
    logo: partners[9],
    bodyImage: card_body_imgs[4],
    bgColor: "#212529",
  },
  {
    id: "2",
    title: "We Hear You",
    description: "We Hear You",
    color: "#fff",
    logo: partners[15],
    bodyImage: card_body_imgs[8],
    bgColor: "linear-gradient(156.01deg, #EF764A 0.69%, #122374 108.05%)",
  },
  {
    id: "3",
    title: "NotiSecure",
    description: "NotiSecure",
    color: "#fff",
    logo: partners[10],
    bodyImage: card_body_imgs[5],
    bgColor: "linear-gradient(178.5deg, #F8A389 1.28%, #FFFFFF 52.33%)",
  },
  {
    id: "4",
    title: "Hybee",
    description: "Hybee",
    color: "#000",
    logo: partners[8],
    bodyImage: card_body_imgs[3],
    bgColor: "#fff",
  },
  {
    id: "5",
    title: "Bug Hunty",
    description: "Bug Hunty",
    color: "#fff",
    logo: partners[0],
    bodyImage: card_body_imgs[0],
    bgColor: "linear-gradient(180deg, #000000 0%, #383833 100%)",
  },
  {
    id: "6",
    title: "Cookie Seal",
    description: "Cookie Seal",
    color: "#000",
    logo: partners[3],
    bodyImage: card_body_imgs[1],
    bgColor: "#fff",
  },
  {
    id: "7",
    title: "Recommaster",
    description: "Recommaster",
    color: "#000",
    logo: partners[11],
    bodyImage: card_body_imgs[6],
    bgColor: "linear-gradient(180deg, #FFFFFF 64.54%, #33B669 132.67%)",
  },
  {
    id: "8",
    title: "3pmetrics",
    description: "3pmetrics",
    color: "#000",
    logo: partners[13],
    bodyImage: card_body_imgs[7],
    bgColor:
      "linear-gradient(179.94deg, #52BD8C 0.06%, rgba(255, 255, 255, 0) 50.04%), #FFFFFF",
  },
  {
    id: "9",
    title: "SanataBiYer",
    description: "SanataBiYer",
    color: "#000",
    logo: partners[17],
    bodyImage: card_body_imgs[9],
    bgColor: "#fff",
  },
  {
    id: "10",
    title: "Dogus Grup",
    description: "Dogus Grup",
    color: "#000",
    logo: partners[5],
    bodyImage: card_body_imgs[10],
    bgColor: "#fff",
  },
  {
    id: "11",
    title: "D-ONE",
    description: "D-ONE",
    color: "#000",
    logo: partners[4],
    bodyImage: card_body_imgs[11],
    bgColor: "#fff",
  },
];

export default card_infos;
